### ISSUE TITLE
$html->load_file shows errors if a page doesn't exist. 

### ISSUE THREAD

**Issue by naneri** [sunra/php-simple-html-dom-parser#11]
I have a trouble. Using the $html->load_file method, it shows errors if a page doesn't exist. 
The error says: 'Warning: file_get_contents(http://auto.desko.kg/car/24779): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in C:\xampp\htdocs\deskoparse\simple_html_dom.php on line 1080'. Is it possible to add checks to the parser so it could find out if such a page exists, and also why that mthod doesn't return 'True' if a page exists?

**Comment by nicolrx** [comment]
Same problem here, any idea how to solve it?

**Comment by naneri** [comment]
@nicolrx you can first check the page existance with other function/method from another package like guzzle, and only then call `$html->load_file`
