### ISSUE TITLE
Is the selector ' > ' working ?

### ISSUE THREAD

**Issue by YoruNoHikage** [sunra/php-simple-html-dom-parser#15]
I'm trying to select 'td > a span' but it's selecting 'td a span'...

**Comment by leotm** [comment]
Child selectors are not supported.

Also asked later here: [Find immediate descendants with PHP Simple DOM parser](http://stackoverflow.com/q/33191977/1998086)

Alternatives: [How do you parse and process HTML/XML in PHP?]( http://stackoverflow.com/a/3577662/1998086)

Suggested: [PHP Html Parser](https://github.com/paquettg/php-html-parser)
(Originally by this project)

**Comment by YoruNoHikage** [comment]
Thanks for answering this, but it's been two years, I don't even remember why I needed this. xD

**Comment by leotm** [comment]
Just dug up the good ole gem :D

[#22 Suport for child selectors](https://sourceforge.net/p/simplehtmldom/feature-requests/22/)
Created: 2010-11-18

[simplehtmldom.sourceforge.net](http://simplehtmldom.sourceforge.net/) seems pretty high in Google, so reckon n00bs like me will continue to try it until they hit the limitation threshold.
