### ISSUE TITLE
MAX_FILE_SIZE user definition

### ISSUE THREAD

**Issue by insanebits** [sunra/php-simple-html-dom-parser#20]
I've stumble upon edge case where html reached MAX_FILE_SIZE constant, it would be nice to be able to increase it.

It could be implemented really easy just checking if not already defined, then user could redefine it as necessary.

Even better would be exception to know what happened without diving into library code itself.

**Comment by sunra** [comment]
It solved by https://github.com/sunra/php-simple-html-dom-parser/pull/24
