### ISSUE TITLE
HtmlDomParser::file_get_html() returning false for html page

### ISSUE THREAD

**Issue by fatihjy** [sunra/php-simple-html-dom-parser#33]
Hi,

First of all, thanks for this great tool. I'm having a little problem. When I use either HtmlDomParser::file_get_html($urlOfThePage), or get the html of the file with curl and use  HtmlDomParser::file_get_html($str)  **for one specific html page**, those functions return false. They are perfectly working fine with other pages but this one. Why would that be?

Thanks.

**Comment by LoveMyData** [comment]
Increase define('MAX_FILE_SIZE', 600000);

I increased mine from 600000 to 6000000 ( added extra zero at the end)

**Comment by LoveMyData** [comment]
Looks like I have older version of the code.... Just defined('MAX_FILE_SIZE') to a bigger number and it will ignore the default setting in simple_html_dom

**Comment by fatihjy** [comment]
where can I find define('MAX_FILE_SIZE', 600000); ?

**Comment by fatihjy** [comment]
increasing MAX_FILE_SIZE solved my problem. Thanks a lot @LoveMyData

**Comment by LoveMyData** [comment]
define('MAX_FILE_SIZE', 600000);
then 
require "xxxx" or use "xxxxx"
