### ISSUE TITLE
file_get_contents(): stream does not support seeking

### ISSUE THREAD

**Issue by xralphack** [sunra/php-simple-html-dom-parser#37]
I have the following warnings when using this library

Warning: file_get_contents(): stream does not support seeking in vendor/sunra/php-simple-html-dom-parser/Src/Sunra/PhpSimple/simplehtmldom_1_5/simple_html_dom.php on line 81

Warning: file_get_contents(): Failed to seek to position -1 in the stream in vendor/sunra/php-simple-html-dom-parser/Src/Sunra/PhpSimple/simplehtmldom_1_5/simple_html_dom.php on line 81

---------------------------

Can someone gives help?

**Comment by sunra** [comment]
what a PHP versiob you use?

**Comment by sunra** [comment]
In any case i corrected negative offset problem now. Update you version,

**Comment by xralphack** [comment]
php7.0, I am using curl now. Thanks
