### ISSUE TITLE
Parser strips new lines

### ISSUE THREAD

**Issue by ahoiroman** [sunra/php-simple-html-dom-parser#44]
Hello and thank you for your great work,

I'm using php-simple-html-dom-parser in a free project and try to solve a bug that occurred.

This is my code: 

```
 foreach ( $dom->find( 'text' ) as $element ) {
 				if ( !in_array( $element->parent()->tag, [ 'a', 'pre', 'code' ] ) ) {
 					foreach ( $markers as $marker ) {
 						$text               = $marker[ 'text' ];
 						$url                = $marker[ 'url' ];
 						$tip                = strip_tags( $marker[ 'excerpt' ] );
 						$tooltip            = ( $tooltip ? "data-uk-tooltip title='$tip'" : "" );
 						$tmpval             = "tmpval-$i";
 						$element->innertext = preg_replace(
 							'/\b' . preg_quote( $text, "/" ) . '\b/i',
 							"<a href='$url' $hrefclass target='$target' $tmpval>\$0</a>",
 							$element->innertext,
 							1
 						);

 						$element->innertext = str_replace( $tmpval, $tooltip, $element->innertext );
 						$i++;
 					}
 				}
				
 			}
``` 

This code searches for text on a page and replaces words with other words.

It works fine. 

But as I found out, this code is removing new lines from `<pre><code>...</code></pre>`:

This is an example-output using the code above:

```
<pre><code>&lt;div class=&quot;uk-form-row&quot;&gt;     &lt;label class=&quot;uk-form-label&quot;&gt;{{ &#39;Pages&#39; | trans }}&lt;/label&gt;     &lt;div class=&quot;uk-form-controls uk-form-controls-text&quot;&gt;         &lt;input-tree :active.sync=&quot;package.config.nodes&quot;&gt;&lt;/input-tree&gt;     &lt;/div&gt; &lt;/div&gt; </code></pre>
```

This is an example-output without using the code above:

```
<pre><code>&lt;div class=&quot;uk-form-row&quot;&gt;
    &lt;label class=&quot;uk-form-label&quot;&gt;{{ &#39;Pages&#39; | trans }}&lt;/label&gt;
    &lt;div class=&quot;uk-form-controls uk-form-controls-text&quot;&gt;
        &lt;input-tree :active.sync=&quot;package.config.nodes&quot;&gt;&lt;/input-tree&gt;
    &lt;/div&gt;
&lt;/div&gt;
</code></pre>
```

**Comment by jurgenhaas** [comment]
We are having a similar issue that by just using 

```
$html = HtmlDomParser::str_get_html($value);

# ... doing some stuff

$value = $html->root->outertext();
```

that then the preformatted text within pre-elements is not longer in tact as white space got removed.

Not sure why this issue is closed again and would love to see some feedback on wheather we're doing something wrong or if that may be a bug in the library.

**Comment by spantin** [comment]
The issue seems to stem from the parse_attr() function. The function assumes attributes should not contain newlines. Problem is, value and data-* attributes may very well contain new lines that you would like preserved.
Commenting out the str_replace lines in that function will fix your issue.
