### ISSUE TITLE
Does not work on php 7.1

### ISSUE THREAD

**Issue by jericopulvera** [sunra/php-simple-html-dom-parser#47]
when will php 7.1 be supported?

**Comment by ahoiroman** [comment]
Just to be safe: Is this solving the issue https://github.com/nystudio107/seomatic/commit/a91980ed8e5db1504e06274d6290be23dda07985 ?

**Comment by jericopulvera** [comment]
@SPQRInc Sorry but I don't even know what to do with that link.

**Comment by jericopulvera** [comment]
@SPQRInc it doesn't work

**Comment by jericopulvera** [comment]
Turns out it's the problem with php not the simple dom.

fixed it by running this command.

sudo apt-get install -y php7.1-fpm php7.1-cli php7.1-mcrypt php7.1-gd php7.1-mysql \
       php7.1-pgsql php7.1-imap php-memcached php7.1-mbstring php7.1-xml php7.1-curl \
       php7.1-bcmath php7.1-sqlite3 php7.1-xdebug
