### ISSUE TITLE
file_get_html returns false.

### ISSUE THREAD

**Issue by innovationsbg** [sunra/php-simple-html-dom-parser#56]
file_get_html returns false for this URL: `https://tripadvisor.ca/Restaurant_Review-g255344-d724335-Reviews-Dynasty_Chinese_Restaurant-Launceston_Tasmania.html` which can be loaded in the browser, but this URL works fine: 'https://tripadvisor.ca'

**Comment by plonknimbuzz** [comment]
did you try 
```php
<?php
$html = file_get_contents($url);
$dom = HtmlDomParser::str_get_html( $html );
```
