### ISSUE TITLE
Use newest version of simplehtmldom

### ISSUE THREAD

**Issue by rosell-dk** [sunra/php-simple-html-dom-parser#65]
simplehtmldom is currently in [version 1.8.1](https://sourceforge.net/projects/simplehtmldom/files/simplehtmldom/)
Why not use the latest version?

I had trouble with the current version because `mb_detect_encoding` isn't available on all systems. This is fixed in version 1.8.1

**Comment by Kub-AT** [comment]
Here you have 1.8.1
https://github.com/Kub-AT/php-simple-html-dom-parser

**Comment by rosell-dk** [comment]
Seems I already updated and forgot to close this ticket. But thanks anyway :)
