### ISSUE TITLE
Unable to parse HTML

### ISSUE THREAD

**Issue by KitePig** [sunra/php-simple-html-dom-parser#73]
$dom = HtmlDomParser::str_get_html('<p>欢迎来到。这是我的第一篇文章。最先写作吧！</p>');

What is the cause of this mistake?

 ErrorException  : preg_match(): Compilation failed: invalid range in character class at offset 4

  at /Users/enle/app/hyena-cms/vendor/sunra/php-simple-html-dom-parser/Src/Sunra/PhpSimple/simplehtmldom_1_5/simple_html_dom.php:1378
    1374|             $this->char = $this->doc[--$this->pos]; // prev
    1375|             return true;
    1376|         }
    1377|
  > 1378|         if (!preg_match("/^[\w-:]+$/", $tag)) {
    1379|             $node->_[HDOM_INFO_TEXT] = '<' . $tag . $this->copy_until('<>');
    1380|             if ($this->char==='<') {
    1381|                 $this->link_nodes($node, false);
    1382|                 return true;

  Exception trace:

  1   preg_match("/^[\w-:]+$/", "p")
      /Users/enle/app/hyena-cms/vendor/sunra/php-simple-html-dom-parser/Src/Sunra/PhpSimple/simplehtmldom_1_5/simple_html_dom.php:1378

  2   simplehtmldom_1_5\simple_html_dom::read_tag()
      /Users/enle/app/hyena-cms/vendor/sunra/php-simple-html-dom-parser/Src/Sunra/PhpSimple/simplehtmldom_1_5/simple_html_dom.php:1187

  3   simplehtmldom_1_5\simple_html_dom::parse()
      /Users/enle/app/hyena-cms/vendor/sunra/php-simple-html-dom-parser/Src/Sunra/PhpSimple/simplehtmldom_1_5/simple_html_dom.php:1081

  4   simplehtmldom_1_5\simple_html_dom::load("<p>欢迎来到。这是我的第一篇文章。最先写作吧！</p>")
      /Users/enle/app/hyena-cms/vendor/sunra/php-simple-html-dom-parser/Src/Sunra/PhpSimple/simplehtmldom_1_5/simple_html_dom.php:102

  5   simplehtmldom_1_5\str_get_html("<p>欢迎来到。这是我的第一篇文章。最先写作吧！</p>")
      /Users/enle/app/hyena-cms/vendor/sunra/php-simple-html-dom-parser/Src/Sunra/PhpSimple/HtmlDomParser.php:21

  6   call_user_func_array("\simplehtmldom_1_5\str_get_html")
      /Users/enle/app/hyena-cms/vendor/sunra/php-simple-html-dom-parser/Src/Sunra/PhpSimple/HtmlDomParser.php:21

  7   Sunra\PhpSimple\HtmlDomParser::str_get_html("<p>欢迎来到。这是我的第一篇文章。最先写作吧！</p>")
      /Users/enle/app/hyena-cms/app/Service/ArticleFormatter.php:296

  8   App\Service\ArticleFormatter::convertImage(Object(Closure))
      /Users/enle/app/hyena-cms/app/Service/ArticleFormatter.php:91

  9   App\Service\ArticleFormatter::importImage()
      /Users/enle/app/hyena-cms/app/Console/Commands/WpSynchronizationImage.php:50

  10  App\Console\Commands\WpSynchronizationImage::handle()
      /Users/enle/app/hyena-cms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  11  call_user_func_array([])
      /Users/enle/app/hyena-cms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  12  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      /Users/enle/app/hyena-cms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:90

  13  Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      /Users/enle/app/hyena-cms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:34

  14  Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      /Users/enle/app/hyena-cms/vendor/laravel/framework/src/Illuminate/Container/Container.php:576

  15  Illuminate\Container\Container::call()
      /Users/enle/app/hyena-cms/vendor/laravel/framework/src/Illuminate/Console/Command.php:183

  16  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /Users/enle/app/hyena-cms/vendor/symfony/console/Command/Command.php:255

  17  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /Users/enle/app/hyena-cms/vendor/laravel/framework/src/Illuminate/Console/Command.php:170

  18  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /Users/enle/app/hyena-cms/vendor/symfony/console/Application.php:908

  19  Symfony\Component\Console\Application::doRunCommand(Object(App\Console\Commands\WpSynchronizationImage), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /Users/enle/app/hyena-cms/vendor/symfony/console/Application.php:269

  20  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /Users/enle/app/hyena-cms/vendor/symfony/console/Application.php:145

  21  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /Users/enle/app/hyena-cms/vendor/laravel/framework/src/Illuminate/Console/Application.php:90

  22  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /Users/enle/app/hyena-cms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122

  23  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /Users/enle/app/hyena-cms/artisan:38

**Comment by tfevens** [comment]
This package is not compatible with PHP 7.3 - Check this one out instead: https://github.com/caophihung94/php-simple-html-dom-parser

**Comment by KitePig** [comment]
ok
